Make collapsing (kitchen sink target creation) opt-in (#384)
**Problem**
People regularly create circular import at the package level partly because our tooling doesn't tell them that it's working around this bad behavior.

**Solution**
This introduces a configuration called kitchen_sink_prefixes, which opts in to collapsing for specific package prefixes,
which hopefully acts as a ratchet that we can prevent further bad behaviors.

**Note**
Example error message:

Error: Circular dependency found in the package src/main/java/com/example/cycle.
  src/main/java/com/example, src/main/java/com/example/cycle
  Resolve the cycle, or allow the cycle this by adding kitchen_sink_prefixes in the module config JSON.
---------
Co-authored-by: Jeff Klukas <jeff@klukas.net>